# mypy_test

```bash
$ pipenv run mypy mypy_test.py 
mypy_test.py:43: error: Argument 1 to "add" of "BadCase" has incompatible type "int"; expected "str"
Found 1 error in 1 file (checked 1 source file)
```
